application:
  schema: public
  job:
    sftp-receiving:
      cron: 0/10 * * * * ?
  sftp:
    host: localhost
    port: 9922
    user: sftpuser
    password: pass
    receiveDirectory: /excel
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ${application.schema}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cancellation_add_services
    username: postgres
    password: postgres
  liquibase:
    changeLog: classpath:liquibase/db.changelog-master.xml
    default-schema: ${application.schema}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}